<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_You have no items in your shopping cart_q</name>
   <tag></tag>
   <elementGuidId>edf62d4e-7278-4c34-93df-f9dbd1384bca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#small-searchterms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='small-searchterms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#small-searchterms</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7fd69ad6-bd13-4020-b660-1d67d902a5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2f58c883-c87d-4b0d-aba3-eeccef5b7fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-box-text ui-autocomplete-input</value>
      <webElementGuid>b9ffe9ce-2185-4a2d-b348-4c17336f766b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>small-searchterms</value>
      <webElementGuid>83150b05-1bbc-47e6-953f-98bbb608bc70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c873cd9d-636d-41b0-9263-717380f6a4bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search store</value>
      <webElementGuid>54d39322-ebac-4ebc-a697-ed9b3299645a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>0ed7c5cd-85eb-420a-9fe1-583ff02cac1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;small-searchterms&quot;)</value>
      <webElementGuid>1da00447-3403-47bc-bdfc-cfec3442c213</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='small-searchterms']</value>
      <webElementGuid>c9d9dd55-2655-427f-9068-622dd59be8f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3fe9a593-c256-461b-9935-8f672f605e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'small-searchterms' and @name = 'q']</value>
      <webElementGuid>fef857b2-c103-42b2-ae75-6cec3323fbf0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
