<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Qty</name>
   <tag></tag>
   <elementGuidId>023b3a18-65e0-4d09-a161-40308f4c7cb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.qty-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='product-details-form']/div/div/div[2]/div[6]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Qty:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>05c24bdf-efe0-4ce2-9dbd-d8c4da98c548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qty-label</value>
      <webElementGuid>766ed06c-8a01-476b-bb49-6f33d306d615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>addtocart_36_EnteredQuantity</value>
      <webElementGuid>d058c272-b5dd-4c5b-a141-54891119a001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Qty:</value>
      <webElementGuid>3d6e84b8-910f-49e1-b53e-c7e33b6a5b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-details-form&quot;)/div[1]/div[@class=&quot;product-essential&quot;]/div[@class=&quot;overview&quot;]/div[@class=&quot;add-to-cart&quot;]/div[@class=&quot;add-to-cart-panel&quot;]/label[@class=&quot;qty-label&quot;]</value>
      <webElementGuid>247cffe7-380e-4fe3-a834-ee81ff39d70c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div/div[2]/div[6]/div/label</value>
      <webElementGuid>1b87cd03-cb6d-4b0f-8a08-62b56f002427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add your review'])[1]/following::label[1]</value>
      <webElementGuid>34b6d5f7-3c1d-420f-9b0f-124cbcc05546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/following::label[1]</value>
      <webElementGuid>a38313b1-83e8-45d5-b545-432445979947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product tags'])[1]/preceding::label[1]</value>
      <webElementGuid>59e07e1e-0fbf-4ff6-8909-32d15a2e12bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cool'])[1]/preceding::label[1]</value>
      <webElementGuid>77b23289-9d25-43f6-bc9e-775c66a7a571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Qty:']/parent::*</value>
      <webElementGuid>7b20e587-2b6d-42f1-984a-9206e34c47f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>afe653c6-587c-4980-925c-034764180973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Qty:' or . = 'Qty:')]</value>
      <webElementGuid>d95733f1-5bb9-46cb-8f2b-980921c68c0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
